### ISSUE TITLE
NPE from preference pane

### ISSUE THREAD

**Issue by abligh** [GoClipse/goclipse#194] opened 2016-03-08 19:31 UTC
A NPE can be produced from the preference pane. To trigger it reliably:
- Open Preferences
- Select Go -> Editor -> Source Highlighting
- Without changing anything or hitting 'Apply', hit OK

Other goclipse and non-goclipse preference panes seem OK.

Versions:

```
Eclipse Version: Mars.2 Release (4.5.2), Build id: 20160218-0600

GoClipse    0.14.1.v201602251806
C/C++ Development Platform  8.8.1.201602051005
C/C++ DSF GDB Debugger Integration  8.8.1.201602051005
Eclipse Platform    4.5.2.v20160212-1500
```

There are actually 2 NPEs in short succession:

```
!ENTRY org.eclipse.jface 4 2 2016-03-08 19:28:35.918
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
    at org.eclipse.swt.graphics.TextLayout.computeRuns(TextLayout.java:222)
    at org.eclipse.swt.graphics.TextLayout.getLineCount(TextLayout.java:998)
    at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:975)
    at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:708)
    at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:211)
    at org.eclipse.swt.custom.StyledTextRenderer.calculateClientArea(StyledTextRenderer.java:229)
    at org.eclipse.swt.custom.StyledText.resetCache(StyledText.java:7955)
    at org.eclipse.swt.custom.StyledText.setForeground(StyledText.java:8799)
    at melnorme.lang.ide.ui.editor.ViewerColorUpdater.doUnconfigureViewer(ViewerColorUpdater.java:69)
    at melnorme.lang.ide.ui.editor.SourceViewerConfigurer.unconfigureViewer(SourceViewerConfigurer.java:61)
    at melnorme.lang.ide.ui.editor.SourceViewerConfigurer$1.dispose(SourceViewerConfigurer.java:47)
    at melnorme.utilbox.ownership.OwnedObjects.disposeAll(OwnedObjects.java:65)
    at melnorme.lang.ide.ui.editor.ProjectionViewerExt.unconfigure(ProjectionViewerExt.java:71)
    at org.eclipse.jface.text.source.SourceViewer.handleDispose(SourceViewer.java:765)
    at org.eclipse.jface.text.source.projection.ProjectionViewer.handleDispose(ProjectionViewer.java:1330)
    at melnorme.lang.ide.ui.editor.ProjectionViewerExt.handleDispose(ProjectionViewerExt.java:83)
    at org.eclipse.jface.text.TextViewer$2.widgetDisposed(TextViewer.java:1802)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.custom.StyledText.handleDispose(StyledText.java:5874)
    at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5684)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1495)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1328)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Canvas.releaseChildren(Canvas.java:334)
    at org.eclipse.swt.widgets.Decorations.releaseChildren(Decorations.java:391)
    at org.eclipse.swt.widgets.Shell.releaseChildren(Shell.java:1391)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Widget.dispose(Widget.java:686)
    at org.eclipse.jface.window.Window.close(Window.java:334)
    at org.eclipse.jface.dialogs.Dialog.close(Dialog.java:990)
    at org.eclipse.jface.preference.PreferenceDialog.close(PreferenceDialog.java:307)
    at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.close(FilteredPreferenceDialog.java:627)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.close(WorkbenchPreferenceDialog.java:145)
    at org.eclipse.jface.preference.PreferenceDialog$12.run(PreferenceDialog.java:947)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
    at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:909)
    at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:409)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.okPressed(WorkbenchPreferenceDialog.java:168)
    at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
    at org.eclipse.jface.window.Window.open(Window.java:803)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
    at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute(ShowPreferencePageHandler.java:59)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:196)
    at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.runCommand(CocoaUIHandler.java:641)
    at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.access$5(CocoaUIHandler.java:628)
    at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler$3.widgetSelected(CocoaUIHandler.java:500)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

!ENTRY org.eclipse.jface 4 0 2016-03-08 19:28:35.919
!MESSAGE java.lang.NullPointerException
!STACK 0
java.lang.NullPointerException
    at org.eclipse.swt.graphics.TextLayout.computeRuns(TextLayout.java:222)
    at org.eclipse.swt.graphics.TextLayout.getLineCount(TextLayout.java:998)
    at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:975)
    at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:708)
    at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:211)
    at org.eclipse.swt.custom.StyledTextRenderer.calculateClientArea(StyledTextRenderer.java:229)
    at org.eclipse.swt.custom.StyledText.resetCache(StyledText.java:7955)
    at org.eclipse.swt.custom.StyledText.setForeground(StyledText.java:8799)
    at melnorme.lang.ide.ui.editor.ViewerColorUpdater.doUnconfigureViewer(ViewerColorUpdater.java:69)
    at melnorme.lang.ide.ui.editor.SourceViewerConfigurer.unconfigureViewer(SourceViewerConfigurer.java:61)
    at melnorme.lang.ide.ui.editor.SourceViewerConfigurer$1.dispose(SourceViewerConfigurer.java:47)
    at melnorme.utilbox.ownership.OwnedObjects.disposeAll(OwnedObjects.java:65)
    at melnorme.lang.ide.ui.editor.ProjectionViewerExt.unconfigure(ProjectionViewerExt.java:71)
    at org.eclipse.jface.text.source.SourceViewer.handleDispose(SourceViewer.java:765)
    at org.eclipse.jface.text.source.projection.ProjectionViewer.handleDispose(ProjectionViewer.java:1330)
    at melnorme.lang.ide.ui.editor.ProjectionViewerExt.handleDispose(ProjectionViewerExt.java:83)
    at org.eclipse.jface.text.TextViewer$2.widgetDisposed(TextViewer.java:1802)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.custom.StyledText.handleDispose(StyledText.java:5874)
    at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5684)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1495)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1328)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:910)
    at org.eclipse.swt.widgets.Canvas.releaseChildren(Canvas.java:334)
    at org.eclipse.swt.widgets.Decorations.releaseChildren(Decorations.java:391)
    at org.eclipse.swt.widgets.Shell.releaseChildren(Shell.java:1391)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
    at org.eclipse.swt.widgets.Control.release(Control.java:2869)
    at org.eclipse.swt.widgets.Widget.dispose(Widget.java:686)
    at org.eclipse.jface.window.Window.close(Window.java:334)
    at org.eclipse.jface.dialogs.Dialog.close(Dialog.java:990)
    at org.eclipse.jface.preference.PreferenceDialog.close(PreferenceDialog.java:307)
    at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.close(FilteredPreferenceDialog.java:627)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.close(WorkbenchPreferenceDialog.java:145)
    at org.eclipse.jface.preference.PreferenceDialog$12.run(PreferenceDialog.java:947)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
    at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:909)
    at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:409)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.okPressed(WorkbenchPreferenceDialog.java:168)
    at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
    at org.eclipse.jface.window.Window.open(Window.java:803)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
    at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute(ShowPreferencePageHandler.java:59)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:196)
    at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.runCommand(CocoaUIHandler.java:641)
    at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.access$5(CocoaUIHandler.java:628)
    at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler$3.widgetSelected(CocoaUIHandler.java:500)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by bruno-medeiros** [comment] 2016-03-15 15:52
I've tried that, but I've been unable to reproduce it. 
What OS are you on? And which base Eclipse package did you use?

**Comment by abligh** [comment] 2016-03-15 17:46
I'm on OS-X 10.9.5

As to 'which base Eclipse package' I'm not quite sure what you mean beyond:

```
Eclipse Version: Mars.2 Release (4.5.2), Build id: 20160218-0600

GoClipse    0.14.1.v201602251806
C/C++ Development Platform  8.8.1.201602051005
C/C++ DSF GDB Debugger Integration  8.8.1.201602051005
Eclipse Platform    4.5.2.v20160212-1500
```

Do you mean version of Eclipse? Or GoClipse? If it's not in the above, where would I find this information?

**Comment by bruno-medeiros** [comment] 2016-03-15 18:08
I mean which Eclipse download package you obtained, since there can be several different ones (with JDT, with CDT, just the base Platform, etc.) 
Alternatively you open Help / Installation Details / Installed Software, and copy/paste the contents of the table there.

**Comment by abligh** [comment] 2016-03-15 18:18
Oh I see. 'Eclipse IDE for Java Developers'. It's been upgraded a number times. 

Here's Help / Installation Details / Installed Software:
  https://gist.github.com/abligh/35a13a4899c2b2ae934b

Here's Help->Installation Details->Configuration:
  https://gist.github.com/abligh/f447d87a9b8d6fe0419d

**Comment by bruno-medeiros** [comment] 2016-04-12 15:30
Ok, I tried with 'Eclipse IDE for Java Developers', but I couldn't replicate it either. I wonder if it's an OSX only issue, could very well be.

**Comment by bruno-medeiros** [comment] 2016-05-31 15:04
Does this still happen with new version?

**Comment by bruno-medeiros** [comment] 2017-03-23 16:33
closing, reopen if necessary

**Closed by bruno-medeiros** 2017-03-23 16:33 UTC
Labels: NEEDS_INFO
