### ISSUE TITLE
Can't run go application in Eclipse Mars (4.5) Windows 7

### ISSUE THREAD

**Issue by vandy** [GoClipse/goclipse#141] opened 2015-07-19 11:48 UTC
I've installed go to `C:\go` (set it as a `%goroot%`), made directory `D:\gopath` (set as `%gopath%`), installed eclipse 4.5, installed goclipse. 
In Go settings set go root, goos = windows, goarch = amd64, gopath=;D:\gopath.
gocode and oracle were installed to D:\gopath and gocode.exe, oracle.exe appeared in %gopath%\bin directory.
Created new Go project: %gopath%\example.com\hello, created hello.go in hello directory:
```
package main
import "fmt"
func main() {
	fmt.Print("Hello.")
}
```

When I select hello.go and press Run as... (Go application) alert is shown: Problem occurred Process path is empty. Although `go run example.com\hello\hello.go` works.

I believe the same configuration worked in previous version of Eclipse and goclipse.

**Comment by bruno-medeiros** [comment] 2015-07-20 13:17
Yup, it's a duplicate of #141

**Comment by bruno-medeiros** [comment] 2015-07-20 13:17
Yup, it's a duplicate of #140

**Comment by bruno-medeiros** [comment] 2015-07-20 13:18
Note the workaround mentioned there:
> A workaround is to put something like "." in the "Go main package" field of the launch.

**Closed by bruno-medeiros** 2015-07-20 13:17 UTC
