### ISSUE TITLE
"Build automatically" doesn't appear to work

### ISSUE THREAD

**Issue by abligh** [GoClipse/goclipse#193] opened 2016-03-08 19:14 UTC
The "build automatically" option on the build menu does not seem to work. I seem to remember this worked a while ago.

The symptom is simply that typing or saving code does not cause a build. Changing "build automatically" from the project menu does nothing. Selecting "Build project" from the project menu correctly builds the project.

There have been no recent entries in the error log.

Versions:

    Eclipse Version: Mars.2 Release (4.5.2), Build id: 20160218-0600

    GoClipse	0.14.1.v201602251806
    C/C++ Development Platform	8.8.1.201602051005
    C/C++ DSF GDB Debugger Integration	8.8.1.201602051005
    Eclipse Platform	4.5.2.v20160212-1500

**Comment by abligh** [comment] 2016-03-08 19:40
OK this is fixed by:

* Build Targets -> "./... #build", Configure Target ...
* Builders -> "Go Project Builder" -> "Edit..."

then ensure "During auto builds" is checked.

I am 99.99% sure I did not uncheck this, so I wonder whether it's an upgrade issue.

**Comment by bruno-medeiros** [comment] 2016-03-09 11:41
It's an upgrade, that functionality was explicitly removed in https://github.com/GoClipse/goclipse/releases/tag/v0.14.0
You can re-add it manually, but by default it's not there. The problem is that "build automatically" has some limitations that make it not work very well, especially in conjunction with other planned features. The good news, is that I am planning to add it back soon, with some modifications. One of them being, the ability to have some build targets enabled just for "build automatically", and others for the full build, normal build.

**Comment by abligh** [comment] 2016-03-09 13:06
Thanks for the update. I'm glad it's coming back. "Build automatically" (or rather the ability to see syntax problems without doing a manual build, which seems to be dependent on "build automatically" at the moment) is really useful.

On 9 Mar 2016, at 11:41, Bruno Medeiros <notifications@github.com> wrote:

> It's an upgrade, that functionality was explicitly removed in https://github.com/GoClipse/goclipse/releases/tag/v0.14.0
> You can re-add it manually, but by default it's not there. The problem is that "build automatically" has some limitations that make it not work very well, especially in conjunction with other planned features. The good news, is that I am planning to add it back soon, with some modifications. One of them being, the ability to have some build targets enabled just for "build automatically", and others for the full build, normal build.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

-- 
Alex Bligh

**Comment by bruno-medeiros** [comment] 2016-03-10 10:21
Syntax problems? You mean compile problems, no? Syntax errors should appear on-the-fly, as you type, without even the need for saving.

**Comment by abligh** [comment] 2016-03-10 10:26
Sorry, *compile* problems, yes.

On 10 Mar 2016, at 10:21, Bruno Medeiros <notifications@github.com> wrote:

> Syntax problems? You mean compile problems, no? Syntax errors should appear on-the-fly, as you type, without even the need for saving.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

-- 
Alex Bligh

**Comment by bruno-medeiros** [comment] 2016-04-12 14:46
Fixed in master. You will have now a build target specifically for the auto-build .

**Closed by bruno-medeiros** 2016-04-12 14:46 UTC
